#!/bin/sh

SCREEN_SIZE=${SCREEN_SIZE:-800x600}
XDISPLAY=:1

Xephyr +extension RANDR -screen ${SCREEN_SIZE} ${XDISPLAY} -ac &
XEPHYR_PID=$!
(
  sleep 1
  env DISPLAY=${XDISPLAY} /usr/bin/qtile -l INFO $@ &
  QTILE_PID=$!
  env DISPLAY=${XDISPLAY} xterm &
  wait $QTILE_PID
  kill $XEPHYR_PID
)
